### ISSUE TITLE
How/where can uploads or dataset organisation be tested?

### ISSUE THREAD

**Issue by dalito** [nfdi4cat/repo4cat#2]
Zenodo or ORCID operate "copies" of their services to allow users to test API access etc. How do we handle this?

Can/should testing be done in a "playgroud" dataverse collection in the [repository](https://repository.nfdi4cat.org/) itself? ...or will there be a separate test-dataverse installation under its own url?

**Comment by vkush** [comment]
A test Dataverse instance will be prepared soon.

Theoretically, we also can create a "playground" area ("dataverse collection") within a current instance - since Dataverse 6.2 is possible to use different PID types for different "dataverse collections" (only 1 type of PID for 1 "dataverse collection" is possible). So, for "playground" area we can have some test PID. It sounds well, but it has also a drawback - all test datasets can be visible on the main page (via visibility settings or via direct "publication" via test PID), so we will have a mix of real and test datasets, what is not so optimal.

That's why priority is a separate instance for tests, which can be also used for teaching courses of NFDI4Cat.

**Comment by dalito** [comment]
Great to hear. I think it is important that people can try without worrying. A separate instance should work perfectly for this.

**Comment by vkush** [comment]
A demo repository is ready to use: 
* https://demo-repository.nfdi4cat.org
* Please read a [documentation](https://github.com/nfdi4cat/repo4cat/tree/main/demo-repository) at first

Here you can find prepared training materials: https://demo-repository.nfdi4cat.org/dataverse/nfdi4cat-training-materials
* a [guideline](https://demo-repository.nfdi4cat.org/dataset.xhtml?persistentId=hdl:21.T11978/4Cat-demo/a3s7-7dwa) provides an introduction to the repo4cat repository and describes the most important working moments with the repository (what is also applicable to the demo repository).
* [collected exercises](https://demo-repository.nfdi4cat.org/dataset.xhtml?persistentId=hdl:21.T11978/4Cat-demo/4dp5-3drr) will help you to get to know Dataverse step by step and then to play with the repository on your own - from creation of own dataverses/datasets to communication with Dataverse using API requests.
